# Generated by Django 2.2 on 2020-02-03 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_areamanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Areamanager',
        ),
    ]
