# Generated by Django 2.2 on 2020-02-03 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_delete_areamanager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Areamanager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameofdepartment', models.CharField(max_length=30)),
                ('partgrp', models.CharField(max_length=30)),
                ('descrptn', models.CharField(max_length=30)),
                ('dte', models.CharField(max_length=30)),
                ('nameofclinicalengr', models.CharField(max_length=30)),
                ('nameofhospital', models.CharField(max_length=30)),
                ('ceid', models.CharField(max_length=30)),
                ('ponumber', models.CharField(max_length=30)),
                ('prnumber', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('approval', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
