# Generated by Django 2.2 on 2020-02-03 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200203_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='areamanager',
            name='approval',
            field=models.BooleanField(default=False),
        ),
    ]
