# Generated by Django 2.2 on 2020-02-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_areamanager_approval'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinicalmanager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameofdepartment', models.CharField(max_length=30)),
                ('partgrp', models.CharField(max_length=30)),
                ('descrptn', models.CharField(max_length=30)),
                ('dte', models.CharField(max_length=30)),
                ('nameofclinicalengr', models.CharField(max_length=30)),
                ('nameofhospital', models.CharField(max_length=30)),
                ('ceid', models.CharField(max_length=30)),
                ('ponumber', models.CharField(max_length=30)),
                ('prnumber', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='areamanager',
            old_name='ceid',
            new_name='approvalbyareamanager',
        ),
        migrations.RemoveField(
            model_name='areamanager',
            name='descrptn',
        ),
        migrations.RemoveField(
            model_name='areamanager',
            name='dte',
        ),
        migrations.RemoveField(
            model_name='areamanager',
            name='nameofclinicalengr',
        ),
        migrations.RemoveField(
            model_name='areamanager',
            name='nameofdepartment',
        ),
        migrations.RemoveField(
            model_name='areamanager',
            name='nameofhospital',
        ),
        migrations.RemoveField(
            model_name='areamanager',
            name='partgrp',
        ),
        migrations.RemoveField(
            model_name='areamanager',
            name='ponumber',
        ),
        migrations.RemoveField(
            model_name='areamanager',
            name='prnumber',
        ),
        migrations.RemoveField(
            model_name='areamanager',
            name='status',
        ),
    ]
