# Generated by Django 2.2 on 2020-02-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200203_0906'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Areamanager',
        ),
        migrations.AddField(
            model_name='clinicalmanager',
            name='approval',
            field=models.BooleanField(default=False),
        ),
    ]
