# Generated by Django 2.2 on 2020-02-03 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_areamanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Areamanager',
        ),
    ]
