# Generated by Django 2.2 on 2020-02-12 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20200210_1002'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clinicalmanager',
        ),
    ]
