# Generated by Django 2.2 on 2020-02-12 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_clinicalmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clinicalmanager',
        ),
    ]
